
import { GoogleGenAI, Type } from "@google/genai";
import { PhishingAnalysis } from "../types";

const API_KEY = process.env.API_KEY || '';

export const analyzeEmail = async (subject: string, body: string): Promise<PhishingAnalysis> => {
  const ai = new GoogleGenAI({ apiKey: API_KEY });
  
  const prompt = `
    Analyze the following email for phishing attempts.
    Subject: ${subject}
    Body: ${body}
    
    Assess sender consistency, urgent/threatening language, suspicious links, grammatical errors, and credential harvesting attempts.
    Also, simulate a 'Classic Model Score' (0-100) that would be generated by a TF-IDF Scikit-Learn Logistic Regression model based on common phishing keywords.
  `;

  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: prompt,
    config: {
      systemInstruction: "You are a world-class cybersecurity expert specializing in email forensics and phishing detection. You provide objective, technical, and actionable security assessments. Return the analysis in a structured JSON format.",
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          riskScore: {
            type: Type.NUMBER,
            description: "A value between 0 and 100 representing the likelihood of phishing.",
          },
          status: {
            type: Type.STRING,
            description: "One of 'Safe', 'Suspicious', or 'Malicious'.",
          },
          redFlags: {
            type: Type.ARRAY,
            items: { type: Type.STRING },
            description: "Specific elements that triggered concern.",
          },
          semanticAnalysis: {
            type: Type.STRING,
            description: "Detailed explanation of why this email is or isn't phishing.",
          },
          recommendations: {
            type: Type.ARRAY,
            items: { type: Type.STRING },
            description: "Steps the user should take.",
          },
          classicModelScore: {
            type: Type.NUMBER,
            description: "Simulated TF-IDF Logistic Regression score (0-100).",
          }
        },
        required: ["riskScore", "status", "redFlags", "semanticAnalysis", "recommendations", "classicModelScore"]
      }
    }
  });

  const resultText = response.text.trim();
  return JSON.parse(resultText) as PhishingAnalysis;
};
